/* =========================================================
   HYDROFOIL PORTFOLIO
   Interactive functionality
========================================================= */


/* =========================================================
   SCROLL REVEAL
========================================================= */

const revealElements =
    document.querySelectorAll(".reveal");


const revealObserver =
    new IntersectionObserver(
        (entries) => {

            entries.forEach((entry) => {

                if (entry.isIntersecting) {

                    entry.target.classList.add("visible");

                    revealObserver.unobserve(entry.target);
                }

            });

        },
        {
            threshold: 0.12
        }
    );


revealElements.forEach((element) => {

    revealObserver.observe(element);

});


/* =========================================================
   CODE VIEWER
========================================================= */

const codeToggle =
    document.querySelector(".code-toggle");


const codeWindow =
    document.querySelector(".code-window");


if (codeToggle && codeWindow) {

    codeToggle.addEventListener("click", () => {

        const isOpen =
            codeWindow.classList.toggle("open");

        codeToggle.setAttribute(
            "aria-expanded",
            isOpen
        );

        codeToggle.textContent =
            isOpen
                ? "Hide code"
                : "View code";

    });

}


/* =========================================================
   ARCHITECTURE EXPLORER
========================================================= */

const architectureTabs =
    document.querySelectorAll(".arch-tab");


const architectureContent =
    document.querySelectorAll(".layer-content");


architectureTabs.forEach((tab) => {

    tab.addEventListener("click", () => {

        const selectedLayer =
            tab.dataset.layer;


        architectureTabs.forEach((item) => {

            item.classList.remove("active");

        });


        architectureContent.forEach((content) => {

            content.classList.remove("active");

        });


        tab.classList.add("active");


        const selectedContent =
            document.querySelector(
                `[data-content="${selectedLayer}"]`
            );


        if (selectedContent) {

            selectedContent.classList.add("active");

        }

    });

});


/* =========================================================
   NAVIGATION SECTION HIGHLIGHTING
========================================================= */

const sections =
    document.querySelectorAll(
        "section[id]"
    );


const navigationLinks =
    document.querySelectorAll(
        ".navbar nav a"
    );


const navigationObserver =
    new IntersectionObserver(
        (entries) => {

            entries.forEach((entry) => {

                if (entry.isIntersecting) {

                    navigationLinks.forEach((link) => {

                        link.classList.remove("active");

                    });


                    const activeLink =
                        document.querySelector(
                            `.navbar nav a[href="#${entry.target.id}"]`
                        );


                    if (activeLink) {

                        activeLink.classList.add("active");

                    }

                }

            });

        },
        {
            rootMargin: "-35% 0px -55% 0px"
        }
    );


sections.forEach((section) => {

    navigationObserver.observe(section);

});


/* =========================================================
   EXTERNAL LINKS
========================================================= */

document
    .querySelectorAll('a[href^="http"]')
    .forEach((link) => {

        link.setAttribute(
            "target",
            "_blank"
        );

        link.setAttribute(
            "rel",
            "noopener noreferrer"
        );

    });


/* =========================================================
   REDUCE MOTION FOR ACCESSIBILITY
========================================================= */

const prefersReducedMotion =
    window.matchMedia(
        "(prefers-reduced-motion: reduce)"
    );


if (prefersReducedMotion.matches) {

    document
        .querySelectorAll(".reveal")
        .forEach((element) => {

            element.classList.add("visible");

        });

}


/* =========================================================
   IMAGE PLACEHOLDER SUPPORT
   Add actual project images later.

   Example:

   assets/images/hydrofoil.jpg
   assets/images/motor.jpg
   assets/images/wiring.jpg
   assets/images/architecture.png
   assets/images/poster.jpg

   No fake images are generated by this website.
========================================================= */
